spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mysocialmedia

server:
  port: 8085

jwt:
  secret: MySocialMediaSecretKeyForJWTTokenGeneration2026VeryLongAndSecure
  expiration: 86400000
